export type AnnualInspectionRequest = {
  printerId: number;
  userId: number;
  sealTampered: boolean;
  notes?: string | null;
  inspectionDate?: string | null;
  mqttRegistroImpresora?: string | null;
  mqttSetDateRevOAt?: number | null;
  mqttNumeroFacturaPrueba?: number | null;
  chkPrecinto?: boolean | null;
  chkEtiquetaFiscal?: boolean | null;
  chkFactura?: boolean | null;
  chkNotaCredito?: boolean | null;
  chkSensorPapel?: boolean | null;
  mqttQrCodigo?: string | null;
  mqttQrRegistro?: string | null;
  mqttQrMac?: string | null;
  mqttQrFecha?: string | null;
};

export type AnnualInspectionResponse = {
  id: number;
  printerId: number;
  userId: number;
  sealTampered: boolean;
  notes: string | null;
  createdAt: string;
  inspectionDate: string;
  mqttRegistroImpresora?: string | null;
  mqttSetDateRevOAt?: number | null;
  mqttNumeroFacturaPrueba?: number | null;
  chkPrecinto?: boolean | null;
  chkEtiquetaFiscal?: boolean | null;
  chkFactura?: boolean | null;
  chkNotaCredito?: boolean | null;
  chkSensorPapel?: boolean | null;
  mqttQrCodigo?: string | null;
  mqttQrRegistro?: string | null;
  mqttQrMac?: string | null;
  mqttQrFecha?: string | null;
};
